version: "3.7"
services:
    # imagem
    base:
        build:
            args:
                user: admin
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - baselayout

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8001:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - baselayout

    # mysql micro 02
    db_base:
        container_name: db_base
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3320:3306
        command: mysqld --character-set-server=utf8mb4
                --collation-server=utf8mb4_unicode_ci
                --default-authentication-plugin=mysql_native_password --sql-mode=""
        networks:
            - baselayout

    # queue micro 02
    # queue_micro_02:
    #     build:
    #         args:
    #             user: admin
    #             uid: 1000
    #         context: ./
    #         dockerfile: Dockerfile
    #     # restart: unless-stopped
    #     command: "php artisan queue:work"
    #     volumes:
    #         - ./:/var/www
    #     depends_on:
    #         - redis_micro_02
    #     networks:
    #         - baselayout

    # #redis
    # redis_micro_02:
    #     image: redis:latest
    #     ports:
    #         - 6379:6379
    #     networks:
    #         - baselayout

networks:
    baselayout:
        driver: bridge
